on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: SSH and Run Commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd {{ secrets.WORK_DIR }} && nvm use 22 && git checkout {{ secrets.MAIN_BRANCH }} && git pull && npm run install && npm run build && sudo service nginx restart"
      - name: cleanup
        run: rm -rf ~/.ssh
        
