on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15'
      - run: npm install
      - run: npm run build
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy to Lightsail
        run: scp -r dist/* {{ secrets.SSH_USER }}@${{ secrets.LIGHTSAIL_IP }}:{{ secrets.WORK_DIR }}
      - name: cleanup
        run: rm -rf ~/.ssh
        
